package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.example.demo.dto.AttendanceDTO;

public interface AttendanceMapper {
	    @Select("SELECT T_CALENDAR.CALENDAR_DATE, T_CALENDAR.WEEKDAY, T_CALENDAR.HOLIDAY_FLG,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_ATTENDANCE.START_TIME ELSE NULL END AS START_TIME,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_ATTENDANCE.END_TIME ELSE NULL END AS END_TIME,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_ATTENDANCE.REST_HOURS_DAY ELSE NULL END AS REST_HOURS_DAY,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_ATTENDANCE.WORKING_HOURS_DAY ELSE NULL END AS WORKING_HOURS_DAY,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_ATTENDANCE.OVERTIME_HOURS_DAY ELSE NULL END AS OVERTIME_HOURS_DAY,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_ATTENDANCE.WORK_CONTENT ELSE NULL END AS WORK_CONTENT,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_STATUS.STATUS_NAME ELSE NULL END AS STATUS_NAME,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_ATTENDANCE.UPDATE_USERID ELSE NULL END AS UPDATE_USERID,\r\n"
	    		+ "       CASE WHEN T_ATTENDANCE.ATTENDANCE_DATE IS NOT NULL THEN T_ATTENDANCE.PLUS_CONTENT ELSE NULL END AS PLUS_CONTENT\r\n"
	    		+ "FROM T_CALENDAR\r\n"
	    		+ "LEFT JOIN T_ATTENDANCE ON T_CALENDAR.CALENDAR_DATE = T_ATTENDANCE.ATTENDANCE_DATE\r\n"
	    		+ "LEFT JOIN T_STATUS ON T_ATTENDANCE.STATUS_ID = T_STATUS.STATUS_ID\r\n"
	    		+ "WHERE T_CALENDAR.CALENDAR_DATE LIKE '2023-06%' AND T_CALENDAR.DEL_FLG = 0;")
	    List<AttendanceDTO> getAttendanceDataForDate(String date);
	}